##
## -- DIESE DATEI NICHT BEARBEITEN --
##
## Die Datei '.env' für die Konfiguration bearbeiten.
## 
##

services:
  pygqa_3.11:
    container_name: pygqa_3.11
    user: "${USE_UID}:${USE_GID}"
    build: .
    command: python ./pygqa.py
    network_mode: "host"
    volumes:
      - .:/pygqa 
